[package]
name = "azul"
version = "0.1.0"
edition = "2021"

[features]
default = []
mlx = ["dep:mlx-rs"]

[dependencies]
rand = "0.9"
mlx-rs = { version = "0.25", optional = true }

[dev-dependencies]
rand = "0.9"
